Fix import error detection of pygraphviz
In the case when matplotlib is not installed the error message below is printed:
    ValueError: must have pygraphviz installed for visualization
This is very confusing because pygraphviz is actually installed and what fails to
import is matplotlib.